import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";

interface ReportSummaryProps {
  candidateName: string;
  summary?: string;
}

export default function ReportSummary({ candidateName, summary }: ReportSummaryProps) {
  return (
    <Card className="mb-6">
      <CardHeader>
        <CardTitle>AI assessment summary</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="p-4 bg-secondary/30 rounded-lg border border-border mb-4">
          <p className="text-xs text-muted-foreground italic mb-2">
            This summary is generated by AI and reflects observed performance
            during the interview. It is a verified assessment of technical depth.
          </p>
        </div>
        <div className="prose prose-sm text-foreground max-w-none">
          <p className="text-sm leading-relaxed whitespace-pre-wrap">
            {summary ||
              `The interview session for ${candidateName} has been evaluated. Review the turn-by-turn transcript and score breakdowns for detailed feedback.`}
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
