import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'

interface ReportSummaryProps {
  candidateName: string
}

export default function ReportSummary({ candidateName }: ReportSummaryProps) {
  return (
    <Card className="mb-6">
      <CardHeader><CardTitle>AI assessment summary</CardTitle></CardHeader>
      <CardContent>
        <div className="p-4 bg-secondary/30 rounded-lg border border-border mb-4">
          <p className="text-xs text-muted-foreground italic mb-2">This summary is generated by AI and reflects observed behaviour during the interview. It is not a hiring recommendation.</p>
        </div>
        <div className="prose prose-sm text-foreground max-w-none">
          <p className="text-sm leading-relaxed mb-4">
            {candidateName} demonstrates a sophisticated, internals-level understanding of the React ecosystem that goes clearly beyond day-to-day usage. He was able to trace state update cycles from trigger to DOM commit without referencing documentation, and his description of Fiber&apos;s scheduling model was technically accurate and well-structured.
          </p>
          <p className="text-sm leading-relaxed mb-4">
            His system design responses showed a pattern of thinking in layers — he consistently reasoned about where state should live, what the right abstraction boundary was, and what failure modes to plan for. These are signals of a candidate who has owned production systems, not just built isolated features.
          </p>
          <p className="text-sm leading-relaxed">
            The primary growth area is breadth outside the frontend stack. When the interview touched on backend coordination patterns or data consistency, {candidateName}&apos;s answers were accurate at a surface level but lacked the depth visible in his frontend responses. For a senior frontend role with minimal backend responsibility, this is unlikely to matter. For a full-stack or tech-lead role, it would be worth exploring in further interviews.
          </p>
        </div>
      </CardContent>
    </Card>
  )
}
